/*
# Seed Data for Aura & Anchor Collections

1. Seed Products with sample luxury watches
2. Seed Banners for homepage hero
3. Seed Testimonials
4. Seed FAQs
*/

INSERT INTO products (name, slug, description, specifications, price, discount_price, stock_quantity, category, brand, featured, best_seller, new_arrival, images) VALUES
('Royal Mariner Chronograph', 'royal-mariner-chronograph', 'A masterpiece of precision engineering, the Royal Mariner Chronograph features a Swiss automatic movement housed in a 316L stainless steel case. The sapphire crystal face reveals intricate mechanical artistry, while the genuine leather strap ensures all-day comfort. Water-resistant to 200 meters.', '{"Movement": "Swiss Automatic", "Case Material": "316L Stainless Steel", "Crystal": "Sapphire", "Water Resistance": "200m", "Strap": "Genuine Leather", "Diameter": "42mm", "Thickness": "12mm", "Power Reserve": "48 hours"}', 2850000, 2500000, 15, 'Chronograph', 'Royal Mariner', true, true, false, ARRAY['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800', 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800']),

('Ocean Master Diver Pro', 'ocean-master-diver-pro', 'Built for the depths, the Ocean Master Diver Pro is the ultimate tool watch for serious divers. Featuring a helium escape valve, unidirectional rotating bezel, and luminous markers for perfect legibility in the darkest waters. A true companion for underwater adventures.', '{"Movement": "Automatic", "Case Material": "Titanium", "Crystal": "Sapphire", "Water Resistance": "500m", "Strap": "Rubber", "Diameter": "44mm", "Bezel": "Ceramic Unidirectional", "Lume": "Super-LumiNova"}', 3200000, null, 8, 'Diver', 'Ocean Master', true, false, true, ARRAY['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800', 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800']),

('Heritage Classic Gold', 'heritage-classic-gold', 'The Heritage Classic Gold pays homage to timeless design with its elegant gold-plated case and minimalist dial. Roman numeral indices and blued steel hands create a sophisticated aesthetic that transcends trends. The perfect dress watch for formal occasions.', '{"Movement": "Quartz", "Case Material": "Gold-Plated Stainless Steel", "Crystal": "Mineral", "Water Resistance": "30m", "Strap": "Crocodile Leather", "Diameter": "38mm", "Thickness": "8mm", "Battery Life": "3 years"}', 1850000, 1650000, 22, 'Dress', 'Heritage', true, true, false, ARRAY['https://images.unsplash.com/photo-1547996663-b0f255ffb89d?w=800', 'https://images.unsplash.com/photo-1507679799987-c73729787bd1?w=800']),

('Aviator Pilot GMT', 'aviator-pilot-gmt', 'Designed for the modern traveler, the Aviator Pilot GMT features a dual-time zone display and a 24-hour bezel. The brushed steel case and anti-reflective sapphire crystal ensure durability and clarity. A reliable companion for pilots and globetrotters alike.', '{"Movement": "Automatic GMT", "Case Material": "Brushed Steel", "Crystal": "AR Sapphire", "Water Resistance": "100m", "Strap": "Stainless Steel Bracelet", "Diameter": "40mm", "GMT Hand": "24-hour", "Crown": "Screw-down"}', 2450000, null, 12, 'Pilot', 'Aviator', false, true, false, ARRAY['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800', 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800']),

('Summit Explorer Titanium', 'summit-explorer-titanium', 'Forged from aerospace-grade titanium, the Summit Explorer is built for extreme conditions. The altimeter, barometer, and compass functions make it indispensable for mountaineers. Despite its rugged capabilities, it maintains an elegant profile suitable for everyday wear.', '{"Movement": "Solar Quartz", "Case Material": "Grade 5 Titanium", "Crystal": "Sapphire", "Water Resistance": "100m", "Strap": "Titanium Bracelet", "Diameter": "43mm", "Sensors": "Altimeter, Barometer, Compass", "Weight": "98g"}', 4100000, 3750000, 6, 'Field', 'Summit', true, false, true, ARRAY['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800']),

('Elegance Rose Gold', 'elegance-rose-gold', 'The Elegance Rose Gold captures feminine sophistication with its rose gold case and mother-of-pearl dial. Diamond hour markers add a touch of luxury, while the slim profile ensures it sits gracefully on the wrist. A statement piece for the modern woman.', '{"Movement": "Automatic", "Case Material": "18K Rose Gold Plated", "Crystal": "Sapphire", "Water Resistance": "50m", "Strap": "Satin", "Diameter": "34mm", "Thickness": "9mm", "Dial": "Mother of Pearl"}', 2100000, 1890000, 18, 'Dress', 'Elegance', false, true, false, ARRAY['https://images.unsplash.com/photo-1507679799987-c73729787bd1?w=800', 'https://images.unsplash.com/photo-1547996663-b0f255ffb89d?w=800']),

('Speed Racer Chronograph', 'speed-racer-chronograph', 'Inspired by motorsport, the Speed Racer Chronograph features a tachymeter scale and split-second timing. The carbon fiber dial and perforated leather strap evoke the spirit of the racetrack. Precision engineering meets adrenaline-fueled design.', '{"Movement": "Automatic Chronograph", "Case Material": "Carbon Fiber & Steel", "Crystal": "Sapphire", "Water Resistance": "100m", "Strap": "Perforated Leather", "Diameter": "41mm", "Functions": "Tachymeter, Split-seconds", "Pushers": "Screw-down"}', 2950000, null, 10, 'Chronograph', 'Speed Racer', false, false, true, ARRAY['https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800', 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800']),

('Navy Admiral Automatic', 'navy-admiral-automatic', 'Paying tribute to naval heritage, the Navy Admiral features a deep blue dial with gold accents and a nautical-inspired bezel. The exhibition caseback reveals the decorated automatic movement. A watch that commands respect on land and sea.', '{"Movement": "Automatic", "Case Material": "Polished Steel", "Crystal": "Sapphire", "Water Resistance": "200m", "Strap": "Navy Canvas", "Diameter": "42mm", "Caseback": "Exhibition", "Bezel": "Nautical 60-minute"}', 2250000, 1990000, 14, 'Diver', 'Navy Admiral', false, true, false, ARRAY['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800']),

('Vintage 1960 Reissue', 'vintage-1960-reissue', 'A faithful recreation of a 1960s classic, the Vintage Reissue captures the charm of a bygone era. The domed acrylic crystal, patina-inspired lume, and hand-wound movement offer an authentic vintage experience. For collectors who appreciate horological history.', '{"Movement": "Hand-wound", "Case Material": "Stainless Steel", "Crystal": "Domed Acrylic", "Water Resistance": "30m", "Strap": "Vintage Leather", "Diameter": "36mm", "Lume": "Patina-style", "Crown": "Onion-style"}', 1650000, null, 20, 'Dress', 'Vintage', false, false, true, ARRAY['https://images.unsplash.com/photo-1547996663-b0f255ffb89d?w=800', 'https://images.unsplash.com/photo-1507679799987-c73729787bd1?w=800']),

('Stealth Tactical Black', 'stealth-tactical-black', 'The Stealth Tactical is engineered for covert operations with its all-black PVD coating and subdued dial. The tritium tubes provide constant illumination without charging. Built to military specifications, this watch is as tough as it is discreet.', '{"Movement": "Automatic", "Case Material": "PVD Coated Steel", "Crystal": "Sapphire", "Water Resistance": "300m", "Strap": "Black NATO", "Diameter": "42mm", "Lume": "Tritium Tubes", "Coating": "Diamond-like Carbon"}', 2750000, 2490000, 9, 'Field', 'Stealth', false, true, false, ARRAY['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800', 'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800']);

INSERT INTO banners (title, subtitle, image, link, active, "order") VALUES
('Timeless Elegance on Every Wrist', 'Discover our curated collection of luxury timepieces crafted for those who appreciate the finer things in life.', 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1600', '/shop', true, 1),
('New Arrivals: The Summit Collection', 'Explore our latest additions featuring titanium cases and advanced sensor technology.', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=1600', '/shop?filter=new', true, 2),
('Heritage Classic: A Legacy of Craftsmanship', 'Experience the art of traditional watchmaking with our Heritage collection.', 'https://images.unsplash.com/photo-1547996663-b0f255ffb89d?w=1600', '/shop?filter=heritage', true, 3);

INSERT INTO testimonials (name, location, comment, rating) VALUES
('James Ochieng', 'Kampala, Uganda', 'The Royal Mariner Chronograph exceeded all my expectations. The craftsmanship is impeccable and the customer service was outstanding. I have received countless compliments on this timepiece.', 5),
('Amina Hassan', 'Nairobi, Kenya', 'I purchased the Elegance Rose Gold as a gift for my mother and she absolutely loves it. The packaging was luxurious and the watch itself is stunning. Aura & Anchor truly understands luxury.', 5),
('David Mwangi', 'Kigali, Rwanda', 'Fast shipping across East Africa and the watch arrived in perfect condition. The Ocean Master Diver Pro is built like a tank. I have been wearing it daily for 6 months without any issues.', 5),
('Sarah Nambafu', 'Dar es Salaam, Tanzania', 'The attention to detail is remarkable. From the website experience to unboxing, everything felt premium. The Heritage Classic Gold is now my go-to dress watch for every formal event.', 4),
('Peter Okello', 'Juba, South Sudan', 'As a collector, I appreciate authenticity and quality. Aura & Anchor delivers both. Their collection is carefully curated and their team is knowledgeable about every piece they sell.', 5);

INSERT INTO faqs (question, answer, "order") VALUES
('How do I know your watches are authentic?', 'Every watch in our collection comes with a certificate of authenticity and manufacturer warranty. We source directly from authorized distributors and renowned watchmakers. Your purchase is 100% guaranteed authentic.', 1),
('What payment methods do you accept?', 'We accept MTN Mobile Money, Airtel Money, cash on delivery, and bank transfers. All payments are processed securely through our encrypted payment gateway.', 2),
('How long does delivery take?', 'Delivery within Uganda takes 1-2 business days. To Kenya, Tanzania, Rwanda, and other East African countries, delivery takes 3-5 business days. All shipments are fully insured.', 3),
('Do you offer warranty on your watches?', 'Yes, all watches come with a minimum 2-year manufacturer warranty. We also provide our own 30-day satisfaction guarantee. If you are not completely satisfied, you can return the watch for a full refund.', 4),
('Can I track my order?', 'Absolutely. Once your order is shipped, you will receive a tracking number via SMS and email. You can also track your order on our website using your order number.', 5),
('Do you offer watch servicing?', 'Yes, we have partnerships with certified watchmakers across East Africa. Contact us for servicing, battery replacement, or strap changes.', 6);
